In [1]:
import numpy as np

In [2]:
np.array([range(i, i+3) for i in [2,4,6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [3]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [4]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [8]:
np.random.random((3,3))

array([[0.57261012, 0.74208921, 0.63949672],
       [0.11821171, 0.66933712, 0.82738051],
       [0.07201689, 0.43945153, 0.55922469]])

In [9]:
np.random.normal(0, 1, (3,3))

array([[-1.27731812, -1.17924395,  0.31578209],
       [ 1.28084149, -1.36987738,  1.04566378],
       [-1.50558076, -0.62993537, -1.18717501]])

In [10]:
np.random.randint(0,10,(3,3))

array([[3, 1, 8],
       [2, 7, 2],
       [1, 4, 1]])

In [11]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [12]:
np.empty(3)

array([1., 1., 1.])

In [13]:
np.zeros(10, dtype='int16')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

In [16]:
np.zeros((4,3),dtype="int16")

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int16)