In [1]:
# For example, a simple selection sort repeatedly finds the minimum value from a list
import numpy as np

def selection_sort(x):
    for i in range(len(x)):
        swap = i + np.argmin(x[i:])
        (x[i], x[swap]) = (x[swap], x[i])
    return x

In [2]:
x = np.array([2, 1, 4, 3, 5])
selection_sort(x)

array([1, 2, 3, 4, 5])

In [4]:
def bogosort(x):
    while np.any(x[:-1] > x[1:]):
        np.random.shuffle(x)
    return x

In [5]:
x = np.array([2, 1, 4, 3, 5])
bogosort(x)

array([1, 2, 3, 4, 5])

In [6]:
# Fast Sorting in NumPy: np.sort and np.argsort
x = np.array([2, 1, 4, 3, 5])
np.sort(x)

array([1, 2, 3, 4, 5])

In [7]:
x.sort()
print(x)

[1 2 3 4 5]


In [8]:
# Sorting along rows or columns
rand = np.random.RandomState(42)
X = rand.randint(0, 10, (4, 6))
print(X)

[[6 3 7 4 6 9]
 [2 6 7 4 3 7]
 [7 2 5 4 1 7]
 [5 1 4 0 9 5]]


In [9]:
# sort each column of X
np.sort(X, axis=0)

array([[2, 1, 4, 0, 1, 5],
       [5, 2, 5, 4, 3, 7],
       [6, 3, 7, 4, 6, 7],
       [7, 6, 7, 4, 9, 9]])

In [10]:
# sort each row of X
np.sort(X, axis=1)

array([[3, 4, 6, 6, 7, 9],
       [2, 3, 4, 6, 7, 7],
       [1, 2, 4, 5, 7, 7],
       [0, 1, 4, 5, 5, 9]])

In [11]:
# Keep in mind that this treats each row or column as an independent array, and any
# relationships between the row or column values will be lost!

In [19]:
# Partial Sorts: Partitioning
# Sometimes we’re not interested in sorting the entire array, but simply want to find the K smallest values in the array
x = np.array([7, 2, 3, 1, 6, 5, 4])
np.partition(x, 3)
# np.partition takes an array and a number K; the result is a new array with the small‐
# est K values to the left of the partition, and the remaining values to the right, in arbi‐
# trary order

array([2, 1, 3, 4, 6, 5, 7])

In [20]:
# Similarly to sorting, we can partition along an arbitrary axis of a multidimensional array
np.partition(X, 2, axis=1)

array([[3, 4, 6, 7, 6, 9],
       [2, 3, 4, 7, 6, 7],
       [1, 2, 4, 5, 7, 7],
       [0, 1, 4, 5, 9, 5]])